### ISSUE TITLE
Paper Update

### ISSUE THREAD

**Issue by thanhlecongg** [soarsmu/soarsmu.github.io#5]
Hi,

I would like to update the following papers to SOAR's publication:

=========================================
Title:  VulCurator: A Vulnerability-Fixing Commit Detector
Authors: Truong Giang Nguyen, Thanh Le-Cong, Hong Jin Kang, and Bach Le and David Lo
Publisher: ESEC/FSE 2022 - Tool Demo Track
Year: 2022
DOI: https://doi.org/10.1145/3540250.3558936
Code: https://github.com/ntgiang71096/VFDetector
PDF: [FSE_VulCurator.pdf](https://thanhlecongg.github.io/pdf/VulCurator.pdf)

=========================================
Title:  AutoPruner: Transformer-Based Call Graph Pruning
Authors: Thanh Le-Cong, Hong Jin Kang, Truong Giang Nguyen, Stefanus Agus Haryono, David Lo, Bach Le and Thang Huynh Quyet
Publisher: ESEC/FSE 2022 - Research Track
Year: 2022
DOI: https://doi.org/10.1145/3540250.3549175
Code: https://github.com/soarsmu/AutoPruner
PDF: [FSE_AutoPruner.pdf](https://thanhlecongg.github.io/pdf/FSE_AutoPruner.pdf)

=========================================
Title:  Chronos: Time-Aware Zero-Shot Identification of Libraries from Vulnerability Reports
Authors: Yunbo Lyu, Thanh Le-Cong, Hong Jin Kang, Ratnadira Widyasari, Zhao Zhipeng, Bach Le, Ming Li and David Lo 
Publisher: ICSE 2023 - Research Track
Year: 2023
Code: https://github.com/soarsmu/Chronos
PDF: [ICSE_Chronos.pdf](https://thanhlecongg.github.io/pdf/ICSE_Chronos.pdf)

=========================================
Title:  Invalidator: Automated Patch Correctness Assessment via Semantic and Syntactic Reasoning
Authors: Thanh Le-Cong, Duc-Minh Luong, Bach Le, David Lo, Nhat Hoa Tran, Quang Huy Bui and Quyet Thang Huynh
Publisher: TSE
Year: 2023
Code: https://github.com/thanhlecongg/Invalidator
PDF: [TSE_Invalidator.pdf](https://thanhlecongg.github.io/pdf/TSE_Invalidator.pdf)

=========================================
Title:  MiDas: Multi-Granularity Detector for Vulnerability Fixes
Authors: Truong Giang Nguyen, Thanh Le-Cong, Hong Jin Kang, Ratnadira Widyasari, Chengran Yang, Zhipeng Zhao, Bowen Xu, Jiayuan Zhou, Xin Xia, Ahmed E. Hassan, Bach Le, and David Lo
Publisher: TSE
Year: 2023
Code: https://github.com/soarsmu/midas
PDF: [TSE_MiDas.pdf](https://thanhlecongg.github.io/pdf/TSE_Midas.pdf)

=========================================
Title:  FFL: Fine grained Fault Localization for Student Programs via Syntactic and Semantic Reasoning
Authors: Thanh-Dat Nguyen, Thanh Le-Cong, Duc-Minh Luong, and Van-Hai Duong, Bach Le, David Lo and Quyet-Thang Huynh
Publisher: ICSME - Research Track
Year: 2022
Code: https://github.com/FFL2022/FFL
PDF: [ICSME_FFL.pdf](https://thanhlecongg.github.io/pdf/ICSME_FFL.pdf)

**Comment by jiekeshi** [comment]
Solved with commit be2e9ab.
